platform :ios, '11.0'
use_frameworks!

# workaround to avoid Xcode 10 caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityKeepAwake', :path => '../../node_modules/@capacitor-community/keep-awake'
  pod 'CapacitorSoundEffect', :path => '../../node_modules/capacitor-sound-effect'
  pod 'CapacitorStockfish', :path => '../../node_modules/capacitor-stockfish'
  # pod 'CapacitorStockfishVariants', :path => '../../node_modules/capacitor-stockfish-variants'
  # Do not delete
end

target 'lichess' do
  capacitor_pods
  # Add your Pods here
  # > https://github.com/ionic-team/capacitor/issues/4570
  # pod 'Firebase/Analytics'
  # pod 'Firebase/Messaging'
  
  pod 'FirebaseCore', '7.11.0'
  pod 'Firebase/Messaging', '7.11.0'
  # <<
end
